name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'  # Update to your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build -- --publish never

      - name: Create Windows Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0-windows-${{ github.run_id }}  # Unique tag name
          name: Release v1.0.0 for Windows
          files: dist/*.exe  # Only include .exe files directly in the dist directory
          token: ${{ secrets.GH_TOKEN }}

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'  # Update to your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build -- --publish never

      - name: Create macOS Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0-macos-${{ github.run_id }}  # Unique tag name
          name: Release v1.0.0 for macOS
          files: dist/*.dmg  # Only include .dmg files directly in the dist directory
          token: ${{ secrets.GH_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'  # Update to your Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build -- --publish never

      - name: Create Linux Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0-linux-${{ github.run_id }}  # Unique tag name
          name: Release v1.0.0 for Linux
          files: dist/*.deb  # Only include .deb files directly in the dist directory
          token: ${{ secrets.GH_TOKEN }}